/**
 * The Git manager's token-only stylesheet and the folder glyph that goes with it.
 *
 * Split out of `client.js` as a package-local chunk: the stylesheet is one big
 * literal array that reads nothing from the entry's scope, and every mount that
 * renders a `git-panel-*` class name has to carry its own copy of it.
 *
 * @module GitPanel/client.style
 */
window.__ModuleLoader__.load({
  id: 'GitPanel',
  chunk: 'client.style.js',
  factory: () => ({
    STYLES: [
      '.git-panel{display:flex;flex-direction:column;height:100%;min-height:0;font-size:12.5px;line-height:1.5;color:var(--dsw-alias-label-primary,#1f2328);background:var(--dsw-alias-bg-base,transparent)}',
      '.git-panel *{box-sizing:border-box}',
      '.git-panel-bar{display:flex;flex-direction:column;gap:6px;flex:none;padding:8px 12px;border-bottom:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.24));background:var(--dsw-alias-bg-layer-1,rgba(128,128,128,.05))}',
      '.git-panel-bar-row{display:flex;align-items:center;gap:8px;min-width:0;flex-wrap:wrap}',
      // The bar pads by 12px, so the field is the 320px column minus that inset
      // to keep the workspace dropdown's right edge on the branch column's edge.
      '.git-panel-field{display:flex;flex-direction:column;gap:2px;min-width:0;flex:1 1 180px;max-width:calc(320px - 12px)}',
      '.git-panel-field-label{font-size:10px;font-weight:600;letter-spacing:.05em;text-transform:uppercase;color:var(--dsw-alias-label-secondary,#57606a)}',
      '.git-panel-field .git-panel-select{width:100%;max-width:none;padding:3px 8px}',
      '.git-panel-branch-chip{flex:none;display:inline-flex;align-items:center;gap:5px;max-width:220px;padding:2px 8px;border-radius:5px;border:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.3));background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.14));color:var(--dsw-alias-label-primary,#1f2328)}',
      '.git-panel-branch-chip-glyph{display:inline-flex;color:var(--dsw-alias-brand-primary,#0969da)}',
      '.git-panel-branch-chip-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:600}',
      '.git-panel-spacer{flex:1;min-width:4px}',
      '.git-panel-select{max-width:260px;border:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.3));background:var(--dsw-alias-bg-layer-1,transparent);color:inherit;border-radius:5px;padding:2px 6px;font:inherit;cursor:pointer}',
      '.git-panel-input{border:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.3));background:var(--dsw-alias-bg-layer-1,transparent);color:inherit;border-radius:5px;padding:2px 7px;font:inherit;min-width:0}',
      '.git-panel-input:focus{outline:none;border-color:var(--dsw-alias-brand-primary,#0969da)}',
      '.git-panel-btn{flex:none;display:inline-flex;align-items:center;justify-content:center;gap:4px;border:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.3));background:var(--dsw-alias-bg-layer-1,transparent);color:inherit;border-radius:5px;padding:2px 8px;font:inherit;cursor:pointer;white-space:nowrap}',
      '.git-panel-btn:hover:not(:disabled){background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.14))}',
      '.git-panel-btn:disabled{opacity:.45;cursor:default}',
      '.git-panel-btn-primary{border-color:color-mix(in srgb,var(--dsw-alias-brand-primary,#0969da) 45%,transparent);background:color-mix(in srgb,var(--dsw-alias-brand-primary,#0969da) 16%,transparent);color:var(--dsw-alias-brand-primary,#0969da)}',
      '.git-panel-btn-primary:hover:not(:disabled){background:color-mix(in srgb,var(--dsw-alias-brand-primary,#0969da) 26%,transparent)}',
      '.git-panel-cols{flex:1;min-height:0;display:flex}',
      '.git-panel-col{display:flex;flex-direction:column;min-height:0;min-width:0}',
      '.git-panel-col-left{width:320px;flex:none;border-right:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.2))}',
      '.git-panel-col-mid{flex:1;min-width:220px}',
      '.git-panel-col-right{width:400px;flex:none;border-left:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.2))}',
      '.git-panel-pane{display:flex;flex-direction:column;min-height:0;overflow:hidden}',
      '.git-panel-pane-top{flex:1 1 46%;border-bottom:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.18))}',
      '.git-panel-pane-grow{flex:1}',
      '.git-panel-pane-head{display:flex;align-items:center;gap:6px;flex:none;flex-wrap:wrap;padding:5px 9px;border-bottom:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.18))}',
      '.git-panel-pane-title{font-weight:600;font-size:11px;letter-spacing:.04em;text-transform:uppercase;color:var(--dsw-alias-label-secondary,#57606a);white-space:nowrap}',
      '.git-panel-count{flex:none;font-size:10.5px;color:var(--dsw-alias-label-secondary,#57606a)}',
      '.git-panel-list{flex:1;min-height:0;overflow:auto;padding:3px 0 8px}',
      '.git-panel-empty{padding:8px 10px;color:var(--dsw-alias-label-secondary,#57606a)}',
      '.git-panel-row{display:flex;align-items:center;gap:7px;padding:3px 10px;cursor:default}',
      '.git-panel-row:hover{background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.1))}',
      '.git-panel-row-sel,.git-panel-row-sel:hover{background:color-mix(in srgb,var(--dsw-alias-brand-primary,#0969da) 18%,transparent)}',
      '.git-panel-branch{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
      '.git-panel-sub{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dsw-alias-label-secondary,#57606a);font-size:11px}',
      '.git-panel-group{display:flex;align-items:center;gap:6px;width:100%;padding:5px 9px;border:0;background:none;color:inherit;font:inherit;cursor:pointer;text-align:left}',
      '.git-panel-group:hover{background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.08))}',
      '.git-panel-caret{flex:none;width:10px;font-size:9px;opacity:.75}',
      '.git-panel-tag{flex:none;padding:0 5px;border-radius:3px;font-size:10px;font-weight:600;border:1px solid color-mix(in srgb,var(--dsw-alias-brand-primary,#0969da) 40%,transparent);background:color-mix(in srgb,var(--dsw-alias-brand-primary,#0969da) 14%,transparent);color:var(--dsw-alias-brand-primary,#0969da)}',
      '.git-panel-chip{flex:none;padding:0 5px;border-radius:3px;font-size:10px;background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.16));color:var(--dsw-alias-label-secondary,#57606a)}',
      '.git-panel-status{flex:none;width:14px;text-align:center;font-weight:700;font-size:11px;font-family:ui-monospace,monospace}',
      '.git-panel-status-M{color:var(--dsw-alias-state-warn-primary,#9a6700)}',
      '.git-panel-status-A{color:var(--dsw-alias-state-success-primary,#1a7f37)}',
      '.git-panel-status-D{color:var(--dsw-alias-state-error-primary,#cf222e)}',
      '.git-panel-status-R{color:var(--dsw-alias-brand-primary,#0969da)}',
      '.git-panel-status-C{color:var(--dsw-alias-brand-primary,#0969da)}',
      '.git-panel-status-U{color:var(--dsw-alias-state-error-primary,#cf222e)}',
      '.git-panel-status-\\?{color:var(--dsw-alias-state-success-primary,#1a7f37)}',
      '.git-panel-check{flex:none;width:14px;height:14px;accent-color:var(--dsw-alias-brand-primary,#0969da);cursor:pointer}',
      '.git-panel-numstat{flex:none;display:flex;gap:4px;font-family:ui-monospace,monospace;font-size:10px}',
      '.git-panel-plus{color:var(--dsw-alias-state-success-primary,#1a7f37)}',
      '.git-panel-minus{color:var(--dsw-alias-state-error-primary,#cf222e)}',
      '.git-panel-commit{display:flex;flex-direction:column;gap:1px;min-width:0;flex:1}',
      '.git-panel-commit-top{display:flex;align-items:center;gap:6px;min-width:0}',
      '.git-panel-subject{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
      '.git-panel-meta{display:flex;gap:7px;overflow:hidden;color:var(--dsw-alias-label-secondary,#57606a);font-size:11px;white-space:nowrap}',
      '.git-panel-mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px}',
      '.git-panel-detail{flex:1 1 46%;min-height:0;display:flex;flex-direction:column;overflow:hidden;border-bottom:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.18))}',
      '.git-panel-detail-head{flex:none;padding:9px 10px;border-bottom:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.18))}',
      '.git-panel-detail-subject{font-weight:600;font-size:13px;margin-bottom:5px;word-break:break-word}',
      '.git-panel-detail-body{margin-top:6px;white-space:pre-wrap;word-break:break-word;color:var(--dsw-alias-label-secondary,#57606a)}',
      '.git-panel-kv{display:grid;grid-template-columns:auto 1fr;gap:2px 10px;font-size:11.5px}',
      '.git-panel-kv-key{color:var(--dsw-alias-label-secondary,#57606a)}',
      '.git-panel-kv-value{overflow:hidden;text-overflow:ellipsis;word-break:break-all}',
      '.git-panel-msg{display:flex;flex-direction:column;gap:6px;flex:none;padding:8px 10px;border-top:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.18))}',
      '.git-panel-textarea{width:100%;min-height:56px;resize:vertical;border:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.3));background:var(--dsw-alias-bg-layer-1,transparent);color:inherit;border-radius:5px;padding:5px 7px;font:inherit}',
      '.git-panel-textarea:focus{outline:none;border-color:var(--dsw-alias-brand-primary,#0969da)}',
      '.git-panel-actions{display:flex;flex-wrap:wrap;gap:6px;align-items:center}',
      '.git-panel-banner{margin:6px 10px;padding:6px 8px;border-radius:5px;word-break:break-word}',
      '.git-panel-banner-error{background:color-mix(in srgb,var(--dsw-alias-state-error-primary,#cf222e) 12%,transparent);color:var(--dsw-alias-state-error-primary,#cf222e)}',
      '.git-panel-banner-ok{background:color-mix(in srgb,var(--dsw-alias-state-success-primary,#1a7f37) 12%,transparent);color:var(--dsw-alias-state-success-primary,#1a7f37)}',
      '.git-panel-banner-warn{background:color-mix(in srgb,var(--dsw-alias-state-warn-primary,#9a6700) 14%,transparent);color:var(--dsw-alias-state-warn-primary,#9a6700)}',
      '.git-panel-sbs-layout{flex:1;min-height:0;display:flex;align-items:stretch}',
      '.git-panel-sbs-scroll{flex:1;min-width:0;min-height:0;overflow:auto}',
      '.git-panel-sbs-wrap{display:flex;align-items:flex-start;min-height:100%}',
      '.git-panel-sbs{flex:1;min-width:0;display:flex;flex-direction:column;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px;line-height:1.55;tab-size:4}',
      '.git-panel-sbs-nav{position:sticky;top:0;align-self:flex-start;flex:none;display:flex;flex-direction:column;width:54px;max-height:80vh;overflow:auto;border-right:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.24));background:var(--dsw-alias-bg-layer-1,rgba(128,128,128,.05))}',
      '.git-panel-sbs-nav-head{position:sticky;top:0;z-index:1;display:flex;align-items:center;justify-content:center;gap:2px;padding:2px 1px;border-bottom:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.2));background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.14))}',
      '.git-panel-sbs-nav-step{flex:none;display:inline-flex;align-items:center;justify-content:center;width:15px;height:15px;padding:0;border:0;border-radius:3px;background:none;color:inherit;font:inherit;font-size:10px;cursor:pointer}',
      '.git-panel-sbs-nav-step:hover:not(:disabled){background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.24))}',
      '.git-panel-sbs-nav-step:disabled{opacity:.35;cursor:default}',
      '.git-panel-sbs-nav-count{flex:none;font-family:ui-monospace,monospace;font-size:9px;color:var(--dsw-alias-label-secondary,#57606a)}',
      '.git-panel-sbs-nav-item{display:flex;align-items:center;justify-content:flex-end;gap:3px;border:0;background:none;color:inherit;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:10px;line-height:1.5;padding:1px 7px;cursor:pointer;white-space:nowrap}',
      '.git-panel-sbs-nav-item:hover{background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.16))}',
      '.git-panel-sbs-nav-current,.git-panel-sbs-nav-current:hover{background:color-mix(in srgb,var(--dsw-alias-brand-primary,#0969da) 24%,transparent)}',
      '.git-panel-sbs-nav-add{color:var(--dsw-alias-state-success-primary,#1a7f37)}',
      '.git-panel-sbs-nav-del{color:var(--dsw-alias-state-error-primary,#cf222e)}',
      '.git-panel-sbs-nav-change{color:var(--dsw-alias-brand-primary,#0969da)}',
      '.git-panel-sbs-overview{position:relative;flex:none;width:14px;overflow:hidden;cursor:pointer;border-left:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.24));background:var(--dsw-alias-bg-layer-1,rgba(128,128,128,.05))}',
      '.git-panel-sbs-overview-view{position:absolute;left:0;right:0;border-radius:2px;background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.22));pointer-events:none}',
      '.git-panel-sbs-mark{position:absolute;left:2px;right:2px;min-height:3px;padding:0;border:0;border-radius:2px;background:var(--dsw-alias-brand-primary,#0969da);cursor:pointer}',
      '.git-panel-sbs-mark-add{background:var(--dsw-alias-state-success-primary,#1a7f37)}',
      '.git-panel-sbs-mark-del{background:var(--dsw-alias-state-error-primary,#cf222e)}',
      '.git-panel-sbs-mark-change{background:var(--dsw-alias-brand-primary,#0969da)}',
      '.git-panel-sbs-mark-current{outline:1px solid var(--dsw-alias-label-primary,#1f2328)}',
      '.git-panel-sbs-row{scroll-margin-top:26px}',
      '.git-panel-sbs-columns{display:grid;grid-template-columns:1fr 1fr;position:sticky;top:0;z-index:1;background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.14));border-bottom:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.24))}',
      '.git-panel-sbs-column{padding:3px 9px;font-family:inherit;font-size:10px;font-weight:600;letter-spacing:.05em;text-transform:uppercase;color:var(--dsw-alias-label-secondary,#57606a)}',
      '.git-panel-sbs-hunk{padding:3px 9px;color:var(--dsw-alias-brand-primary,#0969da);background:var(--dsw-alias-bg-layer-1,rgba(128,128,128,.05))}',
      '.git-panel-sbs-row{display:grid;grid-template-columns:44px minmax(0,1fr) 44px minmax(0,1fr)}',
      '.git-panel-sbs-no{padding:0 6px;text-align:right;color:var(--dsw-alias-label-secondary,#57606a);opacity:.7;background:var(--dsw-alias-bg-layer-1,rgba(128,128,128,.05));user-select:none}',
      '.git-panel-sbs-cell{padding:0 9px;white-space:pre-wrap;word-break:break-word;min-width:0}',
      '.git-panel-sbs-del{background:color-mix(in srgb,var(--dsw-alias-state-error-primary,#cf222e) 14%,transparent);color:var(--dsw-alias-state-error-primary,#cf222e)}',
      '.git-panel-sbs-add{background:color-mix(in srgb,var(--dsw-alias-state-success-primary,#1a7f37) 14%,transparent);color:var(--dsw-alias-state-success-primary,#1a7f37)}',
      '.git-panel-sbs-blank{background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.09))}',
      '.git-panel-ctx{position:fixed;z-index:90;min-width:230px;padding:4px;border-radius:6px;border:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.3));background:var(--dsw-alias-bg-overlay,#fff);box-shadow:0 8px 28px rgba(0,0,0,.24);display:flex;flex-direction:column;gap:1px}',
      '.git-panel-ctx-head{padding:4px 8px 5px;font-size:11px;color:var(--dsw-alias-label-secondary,#57606a);border-bottom:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.2));margin-bottom:3px;word-break:break-all}',
      '.git-panel-ctx-item{display:flex;align-items:center;gap:6px;width:100%;padding:4px 8px;border:0;border-radius:4px;background:none;color:inherit;font:inherit;text-align:left;cursor:pointer}',
      '.git-panel-ctx-item:hover:not(:disabled){background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.16))}',
      '.git-panel-ctx-item:disabled{opacity:.5;cursor:default}',
      '.git-panel-ctx-sep{height:1px;margin:3px 0;background:var(--dsw-alias-border-l1,rgba(128,128,128,.2))}',
      '.git-panel-scrim{position:fixed;inset:0;z-index:89}',
      '.git-panel-dialog{position:fixed;z-index:91;top:50%;left:50%;transform:translate(-50%,-50%);width:min(360px,90vw);display:flex;flex-direction:column;gap:8px;padding:14px;border-radius:8px;border:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.3));background:var(--dsw-alias-bg-overlay,#fff);box-shadow:0 12px 44px rgba(0,0,0,.3)}',
      '.git-panel-dialog-title{font-weight:600}',
      '.git-panel-dialog-actions{display:flex;justify-content:flex-end;gap:7px}',
      '.git-panel-modal{position:fixed;z-index:91;top:50%;left:50%;transform:translate(-50%,-50%);width:min(1180px,94vw);height:min(760px,88vh);display:flex;flex-direction:column;border-radius:8px;border:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.3));background:var(--dsw-alias-bg-overlay,#fff);box-shadow:0 12px 44px rgba(0,0,0,.3);overflow:hidden}',
      '.git-panel-modal-head{flex:none;display:flex;align-items:center;gap:7px;padding:8px 10px;border-bottom:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.2))}',
      '.git-panel-modal-title{font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
      '.git-panel-modal-body{flex:1;min-height:0;display:flex;flex-direction:column;overflow:hidden}',
      '.git-panel-launch{display:flex;flex-direction:column;gap:10px;padding:14px}',
      '.git-panel-launch-title{font-weight:600;font-size:13px}',
      '.git-panel-launch-text{color:var(--dsw-alias-label-secondary,#57606a)}',
      '.git-panel-launch-icon{color:var(--dsw-alias-brand-primary,#0969da)}',
      '.git-panel-launch-actions{display:flex;margin-top:2px}',
      // The configuration card mirrors the built-in settings pages: each group is
      // a section with its own heading, and the controls are the shared field and
      // switch primitives, whose own stylesheet the framework supplies.
      '.git-panel-config-section{min-width:0;padding:16px 0}',
      '.git-panel-config-heading{margin:0;font-size:13px;font-weight:600;line-height:1.5;color:var(--dsw-alias-label-primary,#1f2328)}',
      '.git-panel-config-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(220px,100%),1fr));gap:16px}',
      '.git-panel-config-toggle{display:grid;gap:6px;padding:12px 0}',
      '.git-panel-config-toggle-row{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;font-size:13px;line-height:1.5;color:var(--dsw-alias-label-primary,#1f2328)}',
      '.git-panel-config-toggle-label{display:flex;align-items:center;gap:4px;flex:1;min-width:0}',
      '.git-panel-config-badges{display:inline-flex;flex:none;align-items:center;gap:8px}',
      '.git-panel-config-reset{padding:0;border:0;background:none;font:inherit;font-size:12px;line-height:1.5;color:var(--dsw-alias-label-secondary,#57606a);cursor:pointer}',
      '.git-panel-config-reset:hover:not(:disabled){color:var(--dsw-alias-label-primary,#1f2328)}',
      '.git-panel-config-reset:disabled{cursor:default}',
      // The switch's info button and its disclosure copy the shared field's own
      // rules, so both settings show the same control with the same type.
      '.git-panel-config-help-button{display:inline-flex;flex:none;align-items:center;justify-content:center;width:24px;height:24px;padding:0;border:0;border-radius:6px;background:none;color:var(--dsw-alias-label-tertiary,#8b949e);cursor:pointer}',
      '.git-panel-config-help-button:hover,.git-panel-config-help-button[aria-expanded="true"]{background:var(--dsw-alias-bg-layer-4,rgba(128,128,128,.1));color:var(--dsw-alias-label-secondary,#57606a)}',
      '.git-panel-config-help-button:focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#0969da);outline-offset:1px}',
      '.git-panel-config-help{padding:10px 0 0;font-size:12px;line-height:1.6;color:var(--dsw-alias-label-secondary,#57606a)}',
      '.git-panel-config-help>p{margin:0}',
      '.git-panel-config-help>p+p{margin-top:8px}',
    ].join('\n'),

    GIT_PATH:
      'M5.5 1a2.5 2.5 0 0 0-1 4.79V10.2a2.5 2.5 0 1 0 1 0V5.79A2.5 2.5 0 0 0 5.5 1Zm0 1.5a1 1 0 1 1 0 2 1 1 0 0 1 0-2Zm0 9.25a1 1 0 1 1 0 2 1 1 0 0 1 0-2Zm5.75-8.5a2.5 2.5 0 0 0-1 4.79v.46a3.25 3.25 0 0 1-3.25 3.25h-.4a2.5 2.5 0 1 0 0 1.5h.4a4.75 4.75 0 0 0 4.75-4.75v-.46a2.5 2.5 0 0 0-1-4.79Zm0 1.5a1 1 0 1 1 0 2 1 1 0 0 1 0-2Z',
  }),
})
